version: '3'

services:
  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: 'runestone'
      POSTGRES_USER: 'runestone'
      POSTGRES_DB: 'runestone'

  redis:
    image: redis

  jobe:
    image: runestone/jobeinabox
    build: ./jobeinabox/
    volumes:
      - ./jobeinabox/files:/usr/local/lib/java

  runestone:
    image: runestone/server
    restart: always
    #command: tail -F peanutbutter
    volumes:
      - ./:/srv/web2py/applications/runestone
    links:
      - db
      - redis
      - jobe
    ports:
      - "80:80"
      - "443:443"
    environment:
      POSTGRES_PASSWORD: 'runestone'
      POSTGRES_USER: 'runestone'
      POSTGRES_DB: 'runestone'
      WEB2PY_CONFIG: 'development'
      WEB2PY_MIGRATE: 'Yes'
      DBURL: 'postgresql://runestone:runestone@db/runestone'
      DEV_DBURL: 'postgresql://runestone:runestone@db/runestone'
      TEST_DBURL: 'postgresql://runestone:runestone@db/runestone_test'
      REDIS_URI: 'redis://redis:6379/0'
      RUNESTONE_HOST: '${RUNESTONE_HOST}'
      CERTBOT_EMAIL: '${CERTBOT_EMAIL}'
      BUILD_BOOKS: '${BUILD_BOOKS}'
      RUNESTONE_HOST: 'cs1410.eng.utah.edu'
      CERTBOT_EMAIL: '' # Don't use https
      BUILD_BOOKS: 'yes'
